spring:
  datasource:
    url: jdbc:postgresql://localhost:5944/weeds_db
    username: weeds_user
    password: weeds_pass123
    hikari:
      schema: app
server:
  port: 8090
  servlet:
    context-path: /plantcare-service
logging.level:
    com.querydsl.sql: DEBUG
cache:
  caffeine:
    expireAfterWriteDurationInMinutes: 1
    maximumSize: 2