version: '3.8'
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: sys
    ports:
      - 5944:5432
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080